### PR TITLE
Added instructions on how to play the game

### PR DESCRIPTION
**Pull request by arkmadj**
### What
 - [x] Add instructions on how to play the game
 
 ### How
 - Added a div containing the instruction paragraph
 
 ```js
 <div class="mb-10">
	<p>Hello Stranger 🕵️‍♂️</p>
	<p>
		Are you in search of the mystery fruits🍓? You’ve come to the right place🌴.
		All you have to do is select the mystery fruits in the correct order 1️⃣ 2️⃣ 3️⃣.
	</p>
	<p>
		You have 6 attempts before the fruits are lost forever😞. You can check
		the history tab on the left to see details on your previous selections⌛.
	</p>
        <p>Good luck and Have fun🌟.</p>
</div>
 ```
 
 ### Note
 - My formatter changed some parts of the HomeView.vue

### CODE REVIEW

**Comment by jedymatt** [comment]
Can you make it like a banner that the user can close? And only show it when it is the user's first time to visit the website. Thanks

**Comment by jedymatt** [comment]
Also, if you messed up the formatting, you can run this in the terminal:
```bash
npm run lint
```

**Comment by arkmadj** [comment]
### What
 - [x] Add instructions banner on how to play the game
 
 ### How
 Made these changes to div containing the instruction paragraph
- Added background color
- Added a border
- Added a border radius
- Added a close button for the banner

```diff
```
 

Screen Shot 2022-07-06 at 10 29 28 PM

**Comment by jedymatt** [comment]
There's something weird I don't know how it happened but it seems that your pull request removes the changes I made from #20

**Review by jedymatt — APPROVED** [review]

**Comment by arkmadj** [comment]
Hi. @jedymatt Did you fix the issue on this PR?

**Comment by jedymatt** [comment]
@arkmadj yes, I reverted the issue where you unknowingly removed the code implemented in #22 ,

**Pull request merged**
