### PR TITLE
Feature dark-mode

### PR DESCRIPTION
**Pull request by NicoletaSerban**
Hi. I made a dark theme, The only thing that I couldn't do is the nav bar to be also white.

### CODE REVIEW

**Comment by jedymatt** [comment]
@NicoletaSerban to make the text white on dark mode to the nav bar, you can insert `dark:text-white` class here:

https://github.com/jedymatt/mystery-fruits-js/blob/9f6bff024dc5f93f934e6571976943e65921020e/src/components/AppNavbar.vue#L7

**Comment by NicoletaSerban** [comment]
Thanks. Now it works. I will push the changes now

**Review by NicoletaSerban — COMMENTED** [review]
Hey. Sorry, I'm at the beginning and I thought I could handle it. I tried to make the changes but I get stuck

**Comment by jedymatt** [comment]
That's okay, you can also share where you got stuck, maybe I can help

**Comment by NicoletaSerban** [comment]
I made some changes, hopefully, good changes :) I didn't know what and how to add animation

**Review by jedymatt — APPROVED** [review]

**Pull request merged**
